### ISSUE TITLE
CSC error AD0001 IndexOutOfRangeException

### ISSUE THREAD

**Issue by starosta33** [fluentassertions/fluentassertions.analyzers#400]
### Description

I get exceptions both in Visual Studio and from CLI

> CSC error AD0001: Analyzer 'FluentAssertions.Analyzers.FluentAssertionsAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'. 

```
System.IndexOutOfRangeException : Index was outside the bounds of the array.
   at FluentAssertions.Analyzers.NunitCodeFixProvider.MethodInvocationMatcher.TryGetNext(IOperation operation)
   at FluentAssertions.Analyzers.NunitCodeFixProvider.AssertThatMatcher.Matches(INamedTypeSymbol type,IOperationMatcher[] matchers)
   at FluentAssertions.Analyzers.NunitCodeFixProvider.AssertThatMatcher.Matches(INamedTypeSymbol type,IOperationMatcher[] matchers,MethodInvocationMatcher methodMatcher,IArgumentOperation& argument)
   at FluentAssertions.Analyzers.NunitCodeFixProvider.AssertThatMatcher.Is(String propertyMatcher,MethodInvocationMatcher methodMatcher,IArgumentOperation& argument)
   at FluentAssertions.Analyzers.NunitCodeFixProvider.TryComputeFixForNunitThat(IInvocationOperation invocation,CodeFixContext context,NunitCodeFixContext t)
   at FluentAssertions.Analyzers.NunitCodeFixProvider.TryComputeFixCore(IInvocationOperation invocation,CodeFixContext context,NunitCodeFixContext t,Diagnostic diagnostic)
   at FluentAssertions.Analyzers.TestingFrameworkCodeFixProvider`1.TryComputeFix(IInvocationOperation invocation,CodeFixContext context,TTestContext t,Diagnostic diagnostic)
   at async FluentAssertions.Analyzers.CodeFixProviderBase`1.RegisterCodeFixesAsync[TTestContext](<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.CodeFixes.CodeFixService.GetCodeFixesAsync(<Unknown Parameters>)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

### Complete minimal example reproducing the issue

N/A

### Expected behavior:

no exception

### Actual behavior:

crash in VS / failed build

### Versions

* Which version of Fluent Assertions Analyzers are you using?
0.34.1

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.Net 4.6.1, .Net 6.0, .Net 8.0

### Additional Information

The CLI issue goes away when upgrading the FluentAssertions from 6.12.2 to 7.0.0

**Comment by starosta33** [comment]
I was able to find the particular assertion for one of the reported issues:

it crashes on this simplification:

```
ContainsKey("CallerIdentifier").Should().BeTrue()

**Comment by starosta33** [comment]
And it crashes [here](https://github.com/fluentassertions/fluentassertions.analyzers/blob/2eae82980c0dac8591fa3e2d23d002049bc370c5/src/FluentAssertions.Analyzers/Utilities/OperartionExtensions.cs#L96C1-L96C150)

`invocation.TargetMethod.ContainingType.TypeArguments` is empty
