### ISSUE TITLE
CollectionShouldHaveElementAtCodeFix throws exception

### ISSUE THREAD

**Issue by jnyrup** [fluentassertions/fluentassertions.analyzers#66]
### Description

Applying the codefix for `CollectionShouldHaveElementAtCodeFix`

```csharp
var list = new[] { " FOO " };

list[0].Trim().Should().Be("FOO");
```

gives this stacktrace
```
System.InvalidCastException : Unable to cast object of type 'Microsoft.CodeAnalysis.CSharp.Syntax.InvocationExpressionSyntax' to type 'Microsoft.CodeAnalysis.CSharp.Syntax.ElementAccessExpressionSyntax'.
   at FluentAssertions.Analyzers.NodeReplacement.RemoveAndRetrieveIndexerArgumentsNodeReplacement.ComputeNew(LinkedListNode`1 listNode)
   at FluentAssertions.Analyzers.FluentAssertionsCodeFixProvider.GetNewExpression(ExpressionSyntax expression,NodeReplacement replacement)
   at FluentAssertions.Analyzers.CollectionShouldHaveElementAtCodeFix.GetNewExpression(ExpressionSyntax expression,FluentAssertionsDiagnosticProperties properties)
   at async FluentAssertions.Analyzers.FluentAssertionsCodeFixProvider.RewriteAssertion(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputePreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.CodeActions.CodeAction.GetPreviewOperationsAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedAction.GetPreviewResultAsync(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Editor.Implementation.Suggestions.SuggestedActionWithNestedFlavors.<>c__DisplayClass11_0.<GetPreviewAsync>b__0(<Unknown Parameters>)
   at async Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.PerformFunctionAsync[T](<Unknown Parameters>)
```

### Expected behavior:

The analyzer should probably not be triggered.
At least I see no semantically equivalent using `HaveElementAt()`

### Actual behavior:

The analyzer was triggered.

### Versions

* Fluent Assertions Analyzers 0.11.2
* .NET framework 4.6.1

**Comment by Meir017** [comment]
looks like #68 solved this too :)
